/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "mux2to1.sv:1.1-10.10" *)
module mux2to1(A, B, S, Y);
  (* src = "mux2to1.sv:2.17-2.18" *)
  input A;
  wire A;
  (* src = "mux2to1.sv:3.17-3.18" *)
  input B;
  wire B;
  (* src = "mux2to1.sv:4.17-4.18" *)
  input S;
  wire S;
  (* src = "mux2to1.sv:5.18-5.19" *)
  output Y;
  wire Y;
  assign Y = S ? B : A;
endmodule
