/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "nor_gate.sv:1.1-9.10" *)
module nor_gate(A, B, Y);
  (* src = "nor_gate.sv:7.14-7.17" *)
  wire _0_;
  (* src = "nor_gate.sv:2.11-2.12" *)
  input A;
  wire A;
  (* src = "nor_gate.sv:3.12-3.13" *)
  input B;
  wire B;
  (* src = "nor_gate.sv:4.12-4.13" *)
  output Y;
  wire Y;
  assign Y = ~(* src = "nor_gate.sv:7.12-7.18" *) _0_;
  assign _0_ = A |(* src = "nor_gate.sv:7.14-7.17" *)  B;
endmodule
