/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "xor_gate.sv:1.1-9.10" *)
module xor_gate(A, B, Y);
  (* src = "xor_gate.sv:2.12-2.13" *)
  input A;
  wire A;
  (* src = "xor_gate.sv:3.12-3.13" *)
  input B;
  wire B;
  (* src = "xor_gate.sv:4.12-4.13" *)
  output Y;
  wire Y;
  assign Y = A ^(* src = "xor_gate.sv:7.12-7.17" *)  B;
endmodule
