/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "not_gate.sv:1.1-8.10" *)
module not_gate(A, Y);
  (* src = "not_gate.sv:2.12-2.13" *)
  input A;
  wire A;
  (* src = "not_gate.sv:3.12-3.13" *)
  output Y;
  wire Y;
  assign Y = ~(* src = "not_gate.sv:6.12-6.14" *) A;
endmodule
