/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "half_adder.sv:1.1-11.10" *)
module half_adder(A, B, Sum, Carry);
  (* src = "half_adder.sv:2.17-2.18" *)
  input A;
  wire A;
  (* src = "half_adder.sv:3.17-3.18" *)
  input B;
  wire B;
  (* src = "half_adder.sv:5.18-5.23" *)
  output Carry;
  wire Carry;
  (* src = "half_adder.sv:4.18-4.21" *)
  output Sum;
  wire Sum;
  assign Carry = A & B;
  assign Sum = A ^ B;
endmodule
