/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "nand_gate.sv:1.1-9.10" *)
module nand_gate(A, B, Y);
  (* src = "nand_gate.sv:7.13-7.18" *)
  wire _0_;
  (* src = "nand_gate.sv:2.14-2.15" *)
  input A;
  wire A;
  (* src = "nand_gate.sv:3.14-3.15" *)
  input B;
  wire B;
  (* src = "nand_gate.sv:4.15-4.16" *)
  output Y;
  wire Y;
  assign Y = ~(* src = "nand_gate.sv:7.11-7.19" *) _0_;
  assign _0_ = A &(* src = "nand_gate.sv:7.13-7.18" *)  B;
endmodule
